name: Push

on:
  push:
    branches: [main]

concurrency:
  group: push-main
  cancel-in-progress: false

jobs:
  test:
    name: Build and Test
    uses: ./.github/workflows/build.yml

  publish:
    needs: [test]
    permissions:
      contents: read
      packages: write
    name: Publish latest tag
    uses: ./.github/workflows/publish-latest.yml
